<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ActiviteGeneree;

class ActiviteGenereeController extends Controller
{
    // Controller methods for handling activities generated by the user
    // This could include methods for creating, updating, deleting, and retrieving activities
    // For example:
    
    public function index(Request $request)
    {
        // Logic to retrieve and return all generated activities
        $activities = ActiviteGeneree::getAllActivitesGenerees();
        return response()->json($activities);
    }

    public function show($id)
    {
        // Logic to retrieve a specific generated activity by ID
        $activity = ActiviteGeneree::getActiviteGenereeById($id);
        if ($activity) {
            return response()->json($activity);
        }
        return response()->json(['message' => 'Activity not found'], 404);
    }

    public function store(Request $request)
    {
        $activity = ActiviteGeneree::createActiviteGeneree($request->all());
        return response()->json($activity, 201);

    }

    public function update(Request $request, $id)
    {
        $activity = ActiviteGeneree::getActiviteGenereeById($id, $request->all());
        if ($activity) {
            return response()->json($activity);
        } else {
            return response()->json(['message' => 'Activity not found'], 404);
        }
    }

    public function destroy($id)
    {
        $success = ActiviteGeneree::deleteActiviteGeneree($id);
        if ($success) {
            return response()->json(['message' => 'Activity deleted successfully']);
        } else {
            return response()->json(['message' => 'Activity not found'], 404);
        }
    }
}
